export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  UPLOAD: "/upload",
  STATEMENT_REVIEW: "/statement/:id/review",
  TRANSACTIONS: "/transactions",
  FINANCIAL_PROFILE: "/financial-profile",
  HEALTH_SCORE: "/health-score",
  RISK_PROFILE: "/risk-profile",
  PORTFOLIO: "/portfolio",
  PORTFOLIO_HOLDINGS: "/portfolio-holdings",
  AI_COACH: "/ai-coach",
  INVESTMENT_PLAN: "/investment-plan",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_ACTIVITY: "/admin/activity",
  ADMIN_AUDIT: "/admin/audit",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "/404",
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
