import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const statusStyles = {
    success: 'bg-green-100 text-green-700',
    'in-progress': 'bg-blue-100 text-blue-700',
    failed: 'bg-red-100 text-red-700',
    none: 'bg-gray-100 text-gray-700',
};
export const BackupSettings = ({ backup, onBackupNow, onFrequencyChange, isBackingUp = false }) => {
    return (_jsxs("div", { className: "rounded-xl bg-white p-6 shadow-sm border border-gray-100", children: [_jsx("h3", { className: "mb-4 text-lg font-semibold text-gray-900", children: "Backup Settings" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between rounded-lg bg-gray-50 p-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: "Last Backup" }), _jsx("p", { className: "text-xs text-gray-500", children: backup.lastBackup ?? 'Never' })] }), _jsx("span", { className: `rounded-full px-2.5 py-0.5 text-xs font-medium ${statusStyles[backup.status]}`, children: backup.status })] }), backup.nextScheduled && (_jsxs("p", { className: "text-sm text-gray-600", children: ["Next scheduled: ", _jsx("span", { className: "font-medium", children: backup.nextScheduled })] })), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "Backup Frequency" }), _jsxs("select", { value: backup.frequency, onChange: (e) => onFrequencyChange(e.target.value), className: "w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-indigo-500 focus:ring-indigo-500", children: [_jsx("option", { value: "daily", children: "Daily" }), _jsx("option", { value: "weekly", children: "Weekly" }), _jsx("option", { value: "monthly", children: "Monthly" })] })] }), _jsx("button", { onClick: onBackupNow, disabled: isBackingUp, className: "rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50 transition-colors", children: isBackingUp ? 'Backing up...' : 'Backup Now' })] })] }));
};
