import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const statusStyles = {
    active: 'bg-green-100 text-green-700',
    inactive: 'bg-gray-100 text-gray-700',
    banned: 'bg-red-100 text-red-700',
};
export const UserTable = ({ users, onUserClick, currentPage, totalPages, onPageChange }) => {
    return (_jsxs("div", { className: "rounded-xl bg-white shadow-sm border border-gray-100", children: [_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-gray-100 bg-gray-50", children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Name" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Email" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Role" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Status" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Joined" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: users.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-6 py-8 text-center text-gray-500", children: "No users found" }) })) : (users.map((user) => (_jsxs("tr", { onClick: () => onUserClick?.(user.id), className: "cursor-pointer hover:bg-gray-50 transition-colors", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-900", children: user.name }), _jsx("td", { className: "px-6 py-4 text-gray-600", children: user.email }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: "rounded-full bg-indigo-100 px-2 py-0.5 text-xs font-medium text-indigo-700", children: user.role }) }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `rounded-full px-2 py-0.5 text-xs font-medium ${statusStyles[user.status]}`, children: user.status }) }), _jsx("td", { className: "px-6 py-4 text-gray-500", children: user.createdAt })] }, user.id)))) })] }) }), totalPages > 1 && (_jsxs("div", { className: "flex items-center justify-between border-t border-gray-100 px-6 py-3", children: [_jsx("button", { onClick: () => onPageChange(currentPage - 1), disabled: currentPage <= 1, className: "rounded-lg border border-gray-300 px-3 py-1 text-sm text-gray-700 hover:bg-gray-50 disabled:opacity-50", children: "Previous" }), _jsxs("span", { className: "text-sm text-gray-500", children: ["Page ", currentPage, " of ", totalPages] }), _jsx("button", { onClick: () => onPageChange(currentPage + 1), disabled: currentPage >= totalPages, className: "rounded-lg border border-gray-300 px-3 py-1 text-sm text-gray-700 hover:bg-gray-50 disabled:opacity-50", children: "Next" })] }))] }));
};
