export const ROUTE_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  UPLOAD: "/upload",
  TRANSACTIONS: "/transactions",
  HEALTH_SCORE: "/health-score",
  RISK_PROFILE: "/risk-profile",
  PORTFOLIO: "/portfolio",
  AI_COACH: "/ai-coach",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  NOT_FOUND: "/404",
  UNAUTHORIZED: "/unauthorized",
} as const;
