import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const statusStyles = {
    healthy: 'bg-green-100 text-green-700',
    degraded: 'bg-yellow-100 text-yellow-700',
    down: 'bg-red-100 text-red-700',
};
export const ApiMonitor = ({ endpoints }) => {
    return (_jsxs("div", { className: "rounded-xl bg-white shadow-sm border border-gray-100", children: [_jsx("div", { className: "border-b border-gray-100 px-6 py-4", children: _jsx("h3", { className: "text-lg font-semibold text-gray-900", children: "API Health" }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-50 border-b border-gray-100", children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Endpoint" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Avg Response" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Requests" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Error Rate" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: endpoints.map((ep) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsxs("td", { className: "px-6 py-3", children: [_jsx("span", { className: "mr-2 rounded bg-gray-100 px-1.5 py-0.5 text-xs font-mono font-medium text-gray-600", children: ep.method }), _jsx("span", { className: "text-gray-900", children: ep.path })] }), _jsxs("td", { className: "px-6 py-3 text-gray-600", children: [ep.avgResponseTime, "ms"] }), _jsx("td", { className: "px-6 py-3 text-gray-600", children: ep.requestCount.toLocaleString() }), _jsxs("td", { className: "px-6 py-3 text-gray-600", children: [ep.errorRate, "%"] }), _jsx("td", { className: "px-6 py-3", children: _jsx("span", { className: `rounded-full px-2 py-0.5 text-xs font-medium ${statusStyles[ep.status]}`, children: ep.status }) })] }, `${ep.method}-${ep.path}`))) })] }) })] }));
};
