"""
WealthWise AI - SQLAlchemy Declarative Base & Mixins

Defines:
- Base: SQLAlchemy 2.x DeclarativeBase (all models inherit this)
- UUIDMixin: UUID primary key with auto-generation
- TimestampMixin: created_at, updated_at with DB-side defaults
- SoftDeleteMixin: deleted_at for soft-delete support
"""

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import Boolean, DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    SQLAlchemy 2.x declarative base.
    All ORM models must inherit from this class.
    """

    pass


class UUIDMixin:
    """
    Adds a UUID primary key column 'id'.
    Auto-generated by Python (not DB) for deterministic ID creation
    before DB insert, which is useful for distributed systems.
    """

    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        default=uuid4,
        sort_order=-2,  # Render id first in column definitions
    )


class TimestampMixin:
    """
    Adds created_at and updated_at columns.
    - created_at: set once by the DB on INSERT (server_default)
    - updated_at: set by DB on INSERT, updated on UPDATE (onupdate)
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        sort_order=99,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        sort_order=100,
    )


class SoftDeleteMixin:
    """
    Adds is_deleted flag and deleted_at timestamp.
    Use with repository-level filters to exclude soft-deleted records.
    """

    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        server_default="false",
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
